# Calculating with numbers

In [1]:
1 + 2

3

In [2]:
1 + 2 + 5 - 3

5

In [3]:
1 + 2 * 3

7

In [4]:
(1 + 2) * 3

9

In [5]:
2 / 13

0.15384615384615385

In [6]:
3 ^ 3

27

In [7]:
1e2 / 3

33.333333333333336

In [8]:
64 ^ 20

0

In [9]:
64. ^ 20.

1.329227995784916e36

# Variables

In [10]:
age = 25

25

In [11]:
name = "Bob"

"Bob"

In [12]:
age

25

In [13]:
age = 25;

In [14]:
println(name, age)

Bob25


In [15]:
"I like" * " burritos"

"I like burritos"

In [16]:
println(name*" is ", age)

Bob is 25


## Calculating with variables

In [17]:
age + 3

28

In [18]:
age_in_months = age * 12

300

In [19]:
println("In 10 years "*name*" will be ", age + 10)

In 10 years Bob will be 35


In [20]:
age = age + 3

28

In [21]:
println("In 10 years "*name*" will be ", age + 10)

In 10 years Bob will be 38


In [22]:
x = 3
3x - 2x^2

-9

In [23]:
x = 3
x += 2
println(x)

5


# Excercises

# REPL modes

## Help mode `?`

In [24]:
?*

search: *



```
*(s::Union{AbstractString, AbstractChar}, t::Union{AbstractString, AbstractChar}...) -> AbstractString
```

Concatenate strings and/or characters, producing a [`String`](@ref). This is equivalent to calling the [`string`](@ref) function on the arguments. Concatenation of built-in string types always produces a value of type `String` but other string types may choose to return a string of a different type as appropriate.

# Examples

```jldoctest
julia> "Hello " * "world"
"Hello world"

julia> 'j' * "ulia"
"julia"
```

---

```
*(s::Regex, t::Union{Regex,AbstractString,AbstractChar}) -> Regex
*(s::Union{Regex,AbstractString,AbstractChar}, t::Regex) -> Regex
```

Concatenate regexes, strings and/or characters, producing a [`Regex`](@ref). String and character arguments must be matched exactly in the resulting regex, meaning that the contained characters are devoid of any special meaning (they are quoted with "\Q" and "\E").

!!! compat "Julia 1.3"
    This method requires at least Julia 1.3.


# Examples

```jldoctest
julia> match(r"Hello|Good bye" * ' ' * "world", "Hello world")
RegexMatch("Hello world")

julia> r = r"a|b" * "c|d"
r"(?:a|b)\Qc|d\E"

julia> match(r, "ac") == nothing
true

julia> match(r, "ac|d")
RegexMatch("ac|d")
```

---

```
*(x, y...)
```

Multiplication operator. `x*y*z*...` calls this function with all arguments, i.e. `*(x, y, z, ...)`.

# Examples

```jldoctest
julia> 2 * 7 * 8
112

julia> *(2, 7, 8)
112
```

---

```
*(A::AbstractMatrix, B::AbstractMatrix)
```

Matrix multiplication.

# Examples

```jldoctest
julia> [1 1; 0 1] * [1 0; 1 1]
2×2 Array{Int64,2}:
 2  1
 1  1
```


## Package mode `[`

In [25]:
]status

Status `~/.julia/environments/v1.5/Project.toml`
  [6e4b80f9] BenchmarkTools v0.5.0
  [5ae59095] Colors v0.12.6
  [8f4d0f93] Conda v1.5.0
  [864edb3b] DataStructures v0.18.9
  [31c24e10] Distributions v0.24.15
  [7876af07] Example v0.5.3
  [7a1cc6ca] FFTW v1.3.2
  [e4b2fa32] GaussianRandomFields v2.1.2
  [f67ccb44] HDF5 v0.15.4
  [7073ff75] IJulia v1.23.2
  [da04e1cc] MPI v0.16.1
  [d96e819e] Parameters v0.12.2
  [61cd1fb4] ParticleDA v0.1.0 `~/.julia/dev/ParticleDA`
  [32113eaa] PkgBenchmark v0.2.10
  [91a5bcdd] Plots v1.10.6
  [c3e4b0f8] Pluto v0.12.21
  [c46f51b8] ProfileView v0.6.9
  [438e738f] PyCall v1.92.2
  [d330b81b] PyPlot v2.9.0
  [295af30f] Revise v3.1.14
  [860ef19b] StableRNGs v1.0.0
  [4c63d2b9] StatsFuns v0.9.6
  [fd094767] Suppressor v0.2.0
  [a759f4b9] TimerOutputs v0.5.8
  [b8865327] UnicodePlots v1.3.0
  [ddb6d928] YAML v0.4.6
  [9fa8497b] Future
  [10745b16] Statistics


In [26]:
]add Statistics

   Updating registry at `~/.julia/registries/General`


   Updating git-repo `https://github.com/JuliaRegistries/General.git`


  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`


## Shell mode `;`

In [27]:
;ls -aFlh

total 144
drwxr-xr-x  14 tkoskela  staff   448B 29 Mar 15:40 ./
drwxr-xr-x  28 tkoskela  staff   896B 29 Mar 15:30 ../
-rw-r--r--   1 tkoskela  staff     0B 29 Mar 13:05 .gitkeep
drwxr-xr-x   4 tkoskela  staff   128B 29 Mar 15:30 .ipynb_checkpoints/
-rw-r--r--   1 tkoskela  staff   241B 29 Mar 13:05 01-introduction.md
-rw-r--r--   1 tkoskela  staff   791B 29 Mar 15:30 02-REPL.md
-rw-r--r--   1 tkoskela  staff   613B 29 Mar 15:30 03-types.md
-rw-r--r--   1 tkoskela  staff   354B 29 Mar 15:30 04-dispatch.md
-rw-r--r--   1 tkoskela  staff   404B 29 Mar 13:05 05-compilation.md
-rw-r--r--   1 tkoskela  staff   502B 29 Mar 13:05 06-modules.md
-rw-r--r--   1 tkoskela  staff   283B 29 Mar 13:05 07-features.md
-rw-r--r--   1 tkoskela  staff   452B 29 Mar 13:05 08-packages.md
-rw-r--r--   1 tkoskela  staff    35K 29 Mar 15:40 Episode-02.ipynb
-rw-r--r--   1 tkoskela  staff    72B 29 Mar 15:30 Untitled.ipynb


# Unicode characters

In [28]:
Λ = 4 # \Lambda = 4

4

In [29]:
α = -5 # \alpha = -4

-5

In [30]:
2α + √Λ # \alpha + \sqrt\Lambda

-8.0

In [31]:
pi

π = 3.1415926535897...

In [32]:
π

π = 3.1415926535897...

# Arrays

In [33]:
[1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [34]:
my_array = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [35]:
my_array[2]

2

In [36]:
my_array * 3

3-element Array{Int64,1}:
 3
 6
 9

In [37]:
my_array[2] - my_array[3]

-1

In [38]:
my_array - 2

LoadError: MethodError: no method matching -(::Array{Int64,1}, ::Int64)
For element-wise subtraction, use broadcasting with dot syntax: array .- scalar
Closest candidates are:
  -(::Complex{Bool}, ::Real) at complex.jl:307
  -(::Missing, ::Number) at missing.jl:115
  -(::Base.CoreLogging.LogLevel, ::Integer) at logging.jl:117
  ...

In [39]:
my_array .- 2

3-element Array{Int64,1}:
 -1
  0
  1

In [40]:
my_2d_array = [1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [41]:
my_2d_array[1:2,3]

2-element Array{Int64,1}:
 3
 6

In [42]:
?fill

search: fill fill! finally findall filter filter! filesize filemode isfile



```
fill(x, dims::Tuple)
fill(x, dims...)
```

Create an array filled with the value `x`. For example, `fill(1.0, (5,5))` returns a 5×5 array of floats, with each element initialized to `1.0`.

`dims` may be specified as either a tuple or a sequence of arguments. For example, the common idiom `fill(x)` creates a zero-dimensional array containing the single value `x`.

# Examples

```jldoctest
julia> fill(1.0, (2,3))
2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

julia> fill(42)
0-dimensional Array{Int64,0}:
42
```

If `x` is an object reference, all elements will refer to the same object:

```jldoctest
julia> A = fill(zeros(2), 2);

julia> A[1][1] = 42; # modifies both A[1][1] and A[2][1]

julia> A
2-element Array{Array{Float64,1},1}:
 [42.0, 0.0]
 [42.0, 0.0]
```


In [43]:
fill(pi, (3,3)) ./ 2

3×3 Array{Float64,2}:
 1.5708  1.5708  1.5708
 1.5708  1.5708  1.5708
 1.5708  1.5708  1.5708

In [46]:
using Statistics
Statistics.mean(my_2d_array)

3.5